---

services:
  mkdocs-material:
    image: docker.io/squidfunk/mkdocs-material:latest
    volumes:
      - ./mkdocs-project:/docs
    working_dir: /docs
    command: build

  nginx:
    image: docker.io/nginx:latest
    container_name: public-web-nginx
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    volumes:
      - ./mkdocs-project/site:/usr/share/nginx/html:ro  # Serve the MkDocs build directory
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Use custom config
    depends_on:
      - mkdocs-material  # Wait for the MkDocs container to complete
    restart: unless-stopped